
- name: install packages
  hosts: db
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.apt:
      name: "{{ item }}"
      state: latest
    loop:
    - mysql
    - nginx
    - postfix