
- name: install packages
  hosts: db
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.apt:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop:
    - { name: 'mysql', state: 'latest'} # item
    - { name: 'nginx', state: 'absent'}
    - { name: 'postfix', state: 'absent'}